In [1]:
import numpy as np
import scipy.linalg as LA

In [2]:
#Need a game which takes turn as input, P1 first -> turn = 1
#                                       P2 first -> turn = 2


#Game involves players enter zero's or ones into a Matrix A

#Takes a player input for which a player chooses what a_i,j 
#they wish to enter a 0 (for P1) or a 1 (for P2) into.

#The game continues until the matrix is full
#P1 wins if DetA = 0
#P2 wins if DetA != 0

In [3]:
rng = np.random.default_rng()
n = 3

dets = []

A = np.empty((n,n))
A.fill(5)

def checkx(x, n): #Prevents player from inputting rows or columns outside the matrix
    while True:
        if not (1<=x<=n):
            print()
            print('Nope, choose again!')
            x = int(input(f"Your turn: What row of the {n}x{n} matrix will you enter a 0 into?"))
        else: return x
            

def checky(y, n): #Prevents player from inputting rows or columns outside the matrix
    while True:
        if not (1<=y<=n):
            print()
            print('Nope, choose again!')
            y = int(input(f"What column of the {n}x{n} matrix will you enter a 0 into?"))
        else: return y

def checkDet(A): #Function to check the determinant of A and decide winner
    while True:
        if (LA.det(A)==0):
            print()
            print(f"DetA = {LA.det(A)}, you win!")
            dets.append(LA.det(A))
            return 0
        elif (LA.det(A)!=0):
            print()
            print(f"DetA = {LA.det(A)}, you lose!")
            dets.append(LA.det(A))
            return 0 
        else: return 0
    

    

def game(turn): #Function to play the matrix game
    global A
    if turn == 1:
        print()
        x = int(input(f"Your turn: What row of the {n}x{n} matrix will you enter a 0 into?"))
        x = checkx(x, n)
        y = int(input(f"What column of the {n}x{n} matrix will you enter a 0 into?"))
        y = checky(y, n)
        while True:
            if (A[x-1,y-1]==0) or (A[x-1,y-1]==1):
                print()
                print('A player has already put something there!')
                print()
                x = int(input(f"Your turn: What row of the {n}x{n} matrix will you enter a 0 into?"))
                x = checkx(x, n)
                y = int(input(f"What column of the {n}x{n} matrix will you enter a 0 into?"))
                y = checky(y, n)
            else: 
                A[x-1,y-1]=0
                print()
                print(A, 'Here is the new Matrix!, You put a zero at', f"({x},{y})")
                if (np.all((A==0) | (A ==1))):
                    checkDet(A)
                    return 0
                game(2)
                break
        
    else:
        x = rng.integers(1, n+1)
        y = rng.integers(1, n+1)
        while True:
            if (A[x-1,y-1]==0) or (A[x-1,y-1]==1):
                print()
                #print(f"P2 tried to place a 1 at ({x},{y}) but there was something already there!")
                x = rng.integers(1, n+1)
                y = rng.integers(1, n+1)
            else:
                A[x-1,y-1] = 1      
                print()
                print(f"Player 2's turn, they've inputted a 1 at the co-ordinate {x,y}.")
                print()
                print(A, 'Here is the new Matrix!')
                if (np.all((A==0) | (A ==1))):
                    checkDet(A)
                    return 0
                game(1)
                break
        

        
        
turn = 1              

game(turn)

Your turn: What row of the 3x3 matrix will you enter a 0 into? 3
What column of the 3x3 matrix will you enter a 0 into? 2



[[5. 5. 5.]
 [5. 5. 5.]
 [5. 0. 5.]] Here is the new Matrix!, You put a zero at (3,2)

Player 2's turn, they've inputted a 1 at the co-ordinate (1, 1).

[[1. 5. 5.]
 [5. 5. 5.]
 [5. 0. 5.]] Here is the new Matrix!



Your turn: What row of the 3x3 matrix will you enter a 0 into? 1
What column of the 3x3 matrix will you enter a 0 into? 2



[[1. 0. 5.]
 [5. 5. 5.]
 [5. 0. 5.]] Here is the new Matrix!, You put a zero at (1,2)

Player 2's turn, they've inputted a 1 at the co-ordinate (1, 3).

[[1. 0. 1.]
 [5. 5. 5.]
 [5. 0. 5.]] Here is the new Matrix!



Your turn: What row of the 3x3 matrix will you enter a 0 into? 1
What column of the 3x3 matrix will you enter a 0 into? 3



A player has already put something there!



Your turn: What row of the 3x3 matrix will you enter a 0 into? 2
What column of the 3x3 matrix will you enter a 0 into? 1



[[1. 0. 1.]
 [0. 5. 5.]
 [5. 0. 5.]] Here is the new Matrix!, You put a zero at (2,1)


Player 2's turn, they've inputted a 1 at the co-ordinate (2, 2).

[[1. 0. 1.]
 [0. 1. 5.]
 [5. 0. 5.]] Here is the new Matrix!



Your turn: What row of the 3x3 matrix will you enter a 0 into? 2
What column of the 3x3 matrix will you enter a 0 into? 3



[[1. 0. 1.]
 [0. 1. 0.]
 [5. 0. 5.]] Here is the new Matrix!, You put a zero at (2,3)



Player 2's turn, they've inputted a 1 at the co-ordinate (3, 3).

[[1. 0. 1.]
 [0. 1. 0.]
 [5. 0. 1.]] Here is the new Matrix!



Your turn: What row of the 3x3 matrix will you enter a 0 into? 1
What column of the 3x3 matrix will you enter a 0 into? 3



A player has already put something there!



Your turn: What row of the 3x3 matrix will you enter a 0 into? 3
What column of the 3x3 matrix will you enter a 0 into? 1



[[1. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]] Here is the new Matrix!, You put a zero at (3,1)

DetA = 1.0, you lose!
